version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres1
    ports:
      - 5436:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
